module.exports =
  ARTICLES_RECEIVED: "ARTICLES_RECEIVED"
  ARTICLES_INFINITE_RECEIVED: "ARTICLES_INFINITE_RECEIVED"
  TOP_ARTICLES_RECEIVED: "TOP_ARTICLES_RECEIVED"
  TAG_ARTICLES_RECEIVED: "TAG_ARTICLES_RECEIVED"
  BOOKMARKED_ARTICLES_RECEIVED: "BOOKMARKED_ARTICLES_RECEIVED"
  ARTICLE_DETAIL_RECEIVED: "ARTICLE_DETAIL_RECEIVED"
  NEW_COMMENT_RECEIVED: "NEW_COMMENT_RECEIVED"
  ARTICLE_UPDATE_RECEIVED: "ARTICLE_UPDATE_RECEIVED"

