module.exports =
  ARTICLES_RECEIVED: "ARTICLES_RECEIVED"
  TOP_ARTICLES_RECEIVED: "TOP_ARTICLES_RECEIVED"
  BOOKMARKED_ARTICLES_RECEIVED: "BOOKMARKED_ARTICLES_RECEIVED"
  ARTICLE_DETAIL_RECEIVED: "ARTICLE_DETAIL_RECEIVED"
  NEW_COMMENT_RECEIVED: "NEW_COMMENT_RECEIVED"

