module.exports =
  CURRENT_USER_RECEIVED: "CURRENT_USER_RECEIVED"
  RECEIVED_DRAFTS:"RECEIVED_DRAFTS"
  RECEIVED_PUBLISHED:"RECEIVED_PUBLISHED"
  LOGOUT:"LOGOUT"
  RECEIVED_BOOKMARKS:"RECEIVED_BOOKMARKS"
  RECEIVED_FAVORITES:"RECEIVED_FAVORITES"

